# ============================================
# PIPELINE DE CI — Ingeniería de Software II
# ============================================

name: CI - Ejecutar Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ejecutar-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v5

      - name: Instalar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar los tests
        run: npm test